baseURL = 'https://zcy530.github.io/'
languageCode = 'en-us'
title = "Caiyi's Website"
theme = 'PaperMod'
ShowToc = true
paginate = 4

[params.homeInfoParams]
Title = "Caiyi Zhang"
Hello = "Hello, this is Caiyi Zhang from China, welcome to my website!!"
Content = "I was born in Chongqing in 2000 and graduated with a bachelor's degree in Software Engineering from East China Normal University in Shanghai. Currently, I work as a software engineer at Microsoft, where I am responsible for video processing, camera capture and codec quality for Teams product. As a video engineer, I also have a strong interest in both front-end and back-end development and a passion for researching and learning new technologies. Feel free to contact me."

[[params.socialIcons]]
name = "Github"
url = "<link>"

[[params.socialIcons]]
name = "Instagram"
url = "<link>"

[[params.socialIcons]]
name = "LinkedIn"
url = "<link>"

[params]
  defaultTheme = "light"
  ShowCodeCopyButtons = true
  disableThemeToggle = true
  ShowToc = true
  TocOpen = true

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url="/home/"
    weight = 1

  [[menu.main]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/project/"
    weight = 3
  
  [[menu.main]]
    identifier = "Life"
    name = "Life"
    url = "/life/"
    weight = 4
  
  [[menu.main]]
    identifier = "Archives"
    name = "Archives"
    url = "/Archives/"
    weight = 5